In [1]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
# 훈련 문서와 정답 레이블 정의
docs = [
    'additional income',
    'best price',
    'big bucks',
    'cash bonus',
    'earn extra cash',
    'spring savings certificate',
    'valero gas marketing',
    'all domestic employees',
    'nominations for oct',
    'confirmation from spinner'
]

# 1 = 스팸 메일, 0 = 정상 메일
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [3]:
# 어휘 사전 크기
vocab_size = 50

# 각 문서 안의 단어들을 정수 인코딩
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[24, 5], [14, 1], [18, 4], [8, 33], [41, 4, 8], [26, 11, 43], [49, 6, 45], [34, 26, 34], [2, 13, 25], [24, 25, 44]]


In [4]:
# 입력 시퀀스 길이를 4로 통일
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[24  5  0  0]
 [14  1  0  0]
 [18  4  0  0]
 [ 8 33  0  0]
 [41  4  8  0]
 [26 11 43  0]
 [49  6 45  0]
 [34 26 34  0]
 [ 2 13 25  0]
 [24 25 44  0]]


In [5]:
# 모델 생성
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [6]:
# 모델 컴파일
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [7]:
# 모델 학습
model.fit(padded_docs, labels, epochs=50, verbose=0)

# 모델 평가
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=', accuracy)

정확도= 1.0


In [8]:
# 새로운 문서 테스트
test_doc = ['big income']

encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
[[0.5887818]]
